# Generated by Django 5.2 on 2025-06-01 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CulturalTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_is', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('daily_life', 'Daily Life'), ('social_classes', 'Social Classes'), ('trade', 'Trade & Commerce'), ('art', 'Art & Architecture'), ('literature', 'Literature & Writing'), ('religion', 'Religion & Rituals'), ('science', 'Science & Technology'), ('other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('content_is', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='cultural_topics/')),
                ('civilization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_topics', to='core.civilization')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cultural_topics', to='core.historicalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('domain_is', models.CharField(max_length=100)),
                ('symbols', models.CharField(blank=True, max_length=200)),
                ('symbols_is', models.CharField(blank=True, max_length=200)),
                ('mythology', models.TextField()),
                ('mythology_is', models.TextField()),
                ('cultural_significance', models.TextField()),
                ('cultural_significance_is', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='deities/')),
                ('civilization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deities', to='core.civilization')),
            ],
            options={
                'verbose_name_plural': 'Deities',
                'ordering': ['name_is'],
            },
        ),
        migrations.CreateModel(
            name='Government',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_is', models.TextField()),
                ('examples', models.TextField()),
                ('examples_is', models.TextField()),
                ('characteristics', models.TextField()),
                ('characteristics_is', models.TextField()),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='governments', to='core.historicalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('description_is', models.TextField()),
                ('equipment', models.TextField()),
                ('equipment_is', models.TextField()),
                ('tactics', models.TextField()),
                ('tactics_is', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='military_units/')),
                ('civilization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military_units', to='core.civilization')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='military_units', to='core.historicalperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('birth_date', models.IntegerField(blank=True, null=True)),
                ('death_date', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('ruler', 'Ruler/Emperor'), ('military', 'General/Military Leader'), ('political', 'Politician/Statesman'), ('philosopher', 'Philosopher/Scholar'), ('religious', 'Religious Figure'), ('artist', 'Artist'), ('scientist', 'Scientist'), ('other', 'Other')], max_length=20)),
                ('biography', models.TextField()),
                ('biography_is', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('achievements_is', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='people/')),
                ('civilization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='core.civilization')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='core.historicalperiod')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name_is'],
            },
        ),
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('description_is', models.TextField()),
                ('outcome', models.TextField()),
                ('outcome_is', models.TextField()),
                ('significance', models.TextField()),
                ('significance_is', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='battles/')),
                ('participants', models.ManyToManyField(related_name='battles', to='core.civilization')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battles', to='core.historicalperiod')),
                ('commanders', models.ManyToManyField(related_name='battles', to='reference.person')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_is', models.CharField(max_length=100)),
                ('weapon_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('description_is', models.TextField()),
                ('usage', models.TextField()),
                ('usage_is', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='weapons/')),
                ('civilization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='core.civilization')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='core.historicalperiod')),
            ],
        ),
    ]
